spring:
  application:
    name:
      salvafood
  datasource:
        url:
          ${DB_URL}
        username:
          ${DB_USER}
        password:
          ${DB_PASSWORD}
        driver-class-name: ${DRIVER}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    hibernate:
      ddl-auto:
        update
    show-sql:
      true
    properties:
      hibernate:
        dialect: ${DIALECT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port:
    ${PORT}
  address: ${HOST}

jwt:
  secret:
    ${JWT_SECRET}
  expiration:
    ${JWT_EXPIRATION}

# Configuración común
app:
  upload:
    max-file-size: 100mb

---
# Perfil local
spring:
  config:
    activate:
      on-profile: local

app:
  image:
    storage: local
  upload:
    dir: ${APP_UPLOAD_DIR}

---
# Perfil producción
spring:
  config:
    activate:
      on-profile: production

app:
  image:
    storage: s3

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}